### ISSUE TITLE
v0.30 random inverted evals

### ISSUE THREAD

**Issue by tpoppins** [sgriffin53/chess0.30#17] opened 2019-04-30 00:32 UTC
Raven is prone to report a -999.99 eval randomly, including in positions where it's completely winning. Here's an example, from a game where I had Raven try to convert a tablebase mate-in-12 KRK position (no, I didn't really expect it to succeed -- lots of engines up to 2000 Elo can't) 

```
[Event "?"]
[Site "?"]
[Date "2019.04.29"]
[Round "?"]
[White "Raven 0.30"]
[Black "_SF10"]
[Result "0-1"]
[FEN "7R/5K2/8/5k2/8/8/8/8 w - - 0 1"]
[GameDuration "00:02:38"]
[GameEndTime "2019-04-29T13:58:48.460 Eastern Daylight Time"]
[GameStartTime "2019-04-29T13:56:09.984 Eastern Daylight Time"]
[PlyCount "64"]
[SetUp "1"]
[Termination "abandoned"]
[TimeControl "40/120"]

1. Rh4 {+5.69/10 4.8s} Kg5 {-M32/37 3.8s} 2. Ra4 {+5.79/11 4.6s}
Kf5 {-M28/35 1.1s} 3. Ke8 {+5.66/10 4.4s} Ke5 {-M26/37 4.3s}
4. Rh4 {+5.65/10 4.2s} Kd5 {-M26/37 0.92s} 5. Kf7 {+5.77/9 4.1s}
Ke5 {-M24/37 2.2s} 6. Rg4 {+5.87/9 3.9s} Kf5 {-M28/38 1.3s}
7. Rb4 {+5.68/10 3.8s} Ke5 {-M28/40 3.8s} 8. Ke8 {-999.99/10 3.6s}
Kd5 {-M26/39 1.4s} 9. Kd7 {+5.82/9 3.5s} Kc5 {-M26/41 4.8s}
10. Rh4 {+5.82/10 3.3s} Kd5 {-M24/41 1.3s} 11. Kd8 {+5.82/9 3.2s}
Ke5 {-M24/41 2.3s} 12. Rg4 {+5.82/9 3.1s} Kf6 {-M28/44 1.1s}
13. Rd4 {+5.68/9 2.9s} Ke6 {-M28/43 0.99s} 14. Rf4 {+5.83/9 2.8s}
Ke5 {-M26/46 2.5s} 15. Rg4 {-999.99/10 2.7s} Kf6 {-M28/45 0.98s}
16. Re4 {+5.74/9 2.6s} Kf5 {-M28/47 3.6s} 17. Ra4 {+5.82/9 2.5s}
Ke5 {-M26/46 3.7s} 18. Rh4 {+5.82/9 2.4s} Kd5 {-M26/48 1.4s}
19. Kd7 {+5.65/9 2.3s} Ke5 {-M24/50 3.3s} 20. Ke7 {+5.82/9 2.2s}
Kf5 {-M22/49 2.1s} 21. Kf8 {+5.62/9 2.1s} Kg5 {-M28/45 2.3s}
22. Re4 {+5.82/9 2.0s} Kf6 {-M28/44 1.1s} 23. Rf4+ {+5.68/9 2.0s}
Ke6 {-M28/45 1.5s} 24. Rh4 {+5.64/9 1.9s} Kf5 {-M28/45 1.6s}
25. Ke7 {+5.68/8 1.8s} Ke5 {-M26/50 1.8s} 26. Ra4 {+5.62/9 1.7s}
Kd5 {-M24/53 2.0s} 27. Kd7 {+5.80/8 1.7s} Ke5 {-M22/55 2.6s}
28. Ke8 {+5.65/8 1.6s} Kf5 {-M24/56 1.7s} 29. Rh4 {+5.67/8 1.5s}
Kg5 {-M26/52 1.8s} 30. Rb4 {+5.75/9 1.5s} Kf5 {-M24/58 2.2s}
31. Ra4 {+5.67/8 1.4s} Ke5 {-M26/48 2.0s} 32. Rh4 {+5.69/8 1.4s}
Kd5 {-M26/49 2.4s, White disconnects} 0-1


```

This is the debug log from Cute Chess GUI: 
[raven-030-bad-eval-log.txt](https://github.com/sgriffin53/chess0.30/files/3129586/raven-030-bad-eval-log.txt)

This is a serious issue as it's liable to affect GUI's automatic win/loss adjudication. With my usual adjudication settings Raven could be awarded a loss just a few moves away from mating its opponent should that -999.99 pop up three times in a row.

Note also the disconnect (=crash) at the end of the game. True, in a 320-game blitz test Raven behaved very well, apart from the occasional random -999.99; but you may still want to investigate the cause of the crash.

If the bad eval problem can be fixed quickly enough you could update the exec without changing the version number. If that takes more than a few days or if you plan to add any changes that may affect strength a new version number would be indicated.

HTH
Tirsa@CCRL

**Comment by sgriffin53** [comment] 2019-04-30 01:06
Hi Tirsa,

This has now been fixed. It was caused by the eval running out of time before overwriting the default eval of -999.99 with a new eval.

It's now been fixed by breaking out of the search loop when it runs out of time so it won't search the next level of iterative deepening.

Thanks for bringing the bug to my attention.

Best regards,
Steve

**Closed by sgriffin53** 2019-04-30 01:06 UTC
